name: Build and Release PDF

on:
  push:
    tags:
      - 'v*.*.*'  # Se activa solo en tags de versión (ej. v1.0.0)
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build PDF
        run: |
          cd guia  
          make

      - name: Find PDF
        run: |
          PDF_FILES=$(find guia -type f -name "*.pdf" | tr '\n' ' ')
          echo "PDF_FILES=$PDF_FILES" >> $GITHUB_ENV
        shell: bash

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: built-pdf
          path: ${{ env.PDF_FILES }}


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-pdf
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PDF_FILES }}
          generate_release_notes: true
